FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm config set fetch-retries 5 && npm config set fetch-retry-maxtimeout 120000 && npm install

COPY . .

EXPOSE 3000

RUN npm run build

CMD ["npm", "start"]
